### ISSUE TITLE
FX.h?

### ISSUE THREAD

**Issue by Syzgyn** [costyn/LEDswarm#4]
I've been trying to figure this out on my own, but with no luck.  Where does FX.h come from, and how can I add it to my platform.io environment? 

I thought it was a library part of WLED, but don't seem to have any luck getting that to work.

**Comment by Syzgyn** [comment]
Ok I figured it out.  For anyone else that runs into this problem, I needed to add https://github.com/costyn/FX to the library list, and then inside that library, add easing.h and easing.c from https://github.com/warrenm/AHEasing

**Comment by costyn** [comment]
Hello! My apologies, I didn't see your issue until today. Glad you worked it out. Yes, the library dependencies are a bit wonky, apologies
